# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyTaxMan_Vendor' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  pod 'IQKeyboardManagerSwift'
  pod 'NVActivityIndicatorView'
  pod 'SDWebImage', '~> 4.0'
  pod 'TweeTextField'
  pod 'DLRadioButton'
  pod 'SVPinView', '~> 1.0'
  pod 'GooglePlaces'
  pod 'BetterSegmentedControl', '~> 1.3'
  pod 'WMSegmentControl'
  pod 'FloatRatingView', '~> 4'
  pod 'SinchRTC'
  pod 'Stripe'

  # Pods for MyTaxMan_Vendor

  target 'MyTaxMan_VendorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyTaxMan_VendorUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
